import Footer from "@/components/Footer";
import Header from "@/components/Header";
import House from "@/components/House";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sistema Claro Oscuro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main>
        <House/>
      </main>
      <Footer/>
    </>
  );
}
